language: python
python:
  - '2.7'

install: pip install -r requirements.txt

before_script:
  - psql -c 'create database kyudo;' -U postgres

script: make test

after_success: coveralls

env:
  global:
    - DJANGO_SETTINGS_MODULE=kyudo.settings.testing
    - SECRET_KEY=supersecretkey
    - DB_NAME=kyudo
    - DB_USER=postgres
    - DB_PASS=''
    - DB_HOST=localhost
    - DB_PORT=5432
    - EMAIL_HOST_PASSWORD=''
    - GOOGLE_OAUTH2_KEY=''
    - GOOGLE_OAUTH2_SECRET=''
    - FREEBASE_API_KEY=''

notifications:
  email:
    recipients:
      - benjamin@bengfort.com
    on_success: change
    on_failure: always
